### ISSUE TITLE
error message advapi32.dll

### ISSUE THREAD

**Issue by D-LUFFY89** [nilaoda/TTML.Tool#1]
Is it possible to update a tool that gives me advapi32.dll error message 
on Windows 7 64-bit

**Comment by nilaoda** [comment]
try google

**Comment by Essam3152** [comment]
This is a windows 32bit version from TTML.Tool, It needs dotnet-sdk-5.0.400-win-x86.exe to work.

[TTML.Tool-1.0-win32.zip](https://github.com/nilaoda/TTML.Tool/files/7022899/TTML.Tool-1.0-win32.zip)
